services:
  - type: web
    name: pdffortis-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: AZURE_TRANSLATOR_KEY
        sync: false
      - key: AZURE_TRANSLATOR_REGION
        sync: false
      - key: AZURE_TRANSLATOR_ENDPOINT
        value: https://api.cognitive.microsofttranslator.com
      - key: LIBRE_TRANSLATE_URL
        value: https://libretranslate.de/translate
